---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  depth: 50

steps:
- name: build-linux
  pull: default
  image: debian:stable
  commands:
    - apt install -y qt5-default qt5-qmake libqt5multimedia5 qtmultimedia5-dev
    - sed -i "s/^#DEFINES/DEFINES/" cutecw.pro
    - qmake cutecw.pro
    - make
    - ./make_release.sh linux 

- name: copy linux release
  image: appleboy/drone-scp
  settings:
    host:
      - rainbowdash.lxc.licorn.eu
    user: droneci
    key:
      from_secret: ssh_droneci_key
    target: /home/sites_web/pub.sigpipe.me/bits/projects/CuteCW/
    source:
      - cutecw.linux*.zip
  when:
    branch:
      - master
    event:
      - push
      - tag

- name: build-windows
  pull: default
  image: debian:stable
  commands:
    - echo 'deb https://pkg.mxe.cc/repos/apt bionic main' >> /etc/apt/sources.list.d/mxeapt.list
    - apt update
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys AAA
    - apt-get --no-install-recommends -qq -y install mxe-x86-64-w64-mingw32.shared-qt3d mxe-x86-64-w64-mingw32.shared-qtactiveqt mxe-x86-64-w64-mingw32.shared-qtbase mxe-x86-64-w64-mingw32.shared-qtcanvas3d mxe-x86-64-w64-mingw32.shared-qtcharts mxe-x86-64-w64-mingw32.shared-qtconnectivity mxe-x86-64-w64-mingw32.shared-qtdatavis3d mxe-x86-64-w64-mingw32.shared-qtdeclarative mxe-x86-64-w64-mingw32.shared-qtgamepad mxe-x86-64-w64-mingw32.shared-qtgraphicaleffects mxe-x86-64-w64-mingw32.shared-qtimageformats mxe-x86-64-w64-mingw32.shared-qtlocation mxe-x86-64-w64-mingw32.shared-qtmultimedia mxe-x86-64-w64-mingw32.shared-qtofficeopenxml mxe-x86-64-w64-mingw32.shared-qtpurchasing mxe-x86-64-w64-mingw32.shared-qtquickcontrols mxe-x86-64-w64-mingw32.shared-qtquickcontrols2 mxe-x86-64-w64-mingw32.shared-qtscript mxe-x86-64-w64-mingw32.shared-qtscxml mxe-x86-64-w64-mingw32.shared-qtsensors mxe-x86-64-w64-mingw32.shared-qtserialbus mxe-x86-64-w64-mingw32.shared-qtserialport mxe-x86-64-w64-mingw32.shared-qtservice mxe-x86-64-w64-mingw32.shared-qtsvg mxe-x86-64-w64-mingw32.shared-qtsystems mxe-x86-64-w64-mingw32.shared-qttools mxe-x86-64-w64-mingw32.shared-qttranslations mxe-x86-64-w64-mingw32.shared-qtvirtualkeyboard mxe-x86-64-w64-mingw32.shared-qtwebchannel mxe-x86-64-w64-mingw32.shared-qtwebkit mxe-x86-64-w64-mingw32.shared-qtwebsockets mxe-x86-64-w64-mingw32.shared-qtwinextras mxe-x86-64-w64-mingw32.shared-qtxlsxwriter mxe-x86-64-w64-mingw32.shared-qtxmlpatterns
    - export QT_API=5.9
    - export QT_MXE=true
    - export QT_MXE_ARCH=amd64
    - i686-w64-mingw32.static-qmake-qt5
    - make
    - ./make_release.sh windows

- name: copy windows release
  image: appleboy/drone-scp
  settings:
    host:
      - rainbowdash.lxc.licorn.eu
    user: droneci
    key:
      from_secret: ssh_droneci_key
    target: /home/sites_web/pub.sigpipe.me/bits/projects/CuteCW/
    source:
      - cutecw.windows*.zip
  when:
    branch:
      - master
    event:
      - push
      - tag

- name: notify
  pull: default
  image: plugins/slack
  settings:
    channel: dev
  environment:
    SLACK_WEBHOOK:
      from_secret: SLACK_WEBHOOK
  when:
    event:
    - push
    - tag
    - pull_request
    status:
    - changed
    - failure
    - success
