Cute CW: train yourself

* Introduction

  I've had thoughts for a long time about how we train ourselves in CW
  ("Carrier Wave" otherwise known as Morse Code).  After preparing for a
  presentation about learning CW I realized software could really help
  us out in ways not yet seen.  This is my effort to help decrease the
  pain in training your brain to understand Morse Code.

* Get it!

  You can download the source code or pre-built binaries from:

    http://www.hamtools.org/qtcw/

  You can also access the git repository, provided by githib, from:

    http://www.github.com/hardaker/CuteCW/

* Further Information

  More documentation can be found at:

    http://www.hamtools.org/qtcw/

  The growing list of [[file:docs/CHANGES.org][CHANGES]] and the hopefully shrinking [[file:docs/TODO.org][TODO list]]

* Compiling It

  CuteCW is a Qt5 based program.  That means to compile it you'll need
  some distribution of [[http://qt.nokia.com/][Qt5]].  You can download any of the recent Qt SDK
  sets and open the cutecw.pro file using qtcreator, which will then
  be able to compile and edit the code.  Or, if you want to compile it
  via a terminal you can try the following steps:

  1. edit cutecw.pro to enable portable build if needed (this will set config file to working dir of run app)
  2. qmake
  3. make
  4. optionally: make install
